# code: language=ansible
---
- name: Set krew bin path (linux)
  when: (ansible_os_family | lower) == 'redhat'
  ansible.builtin.set_fact:
    krew_bin: /home/linuxbrew/.linuxbrew/bin/kubectl-krew

- name: Set krew bin path (mac)
  when: (ansible_os_family | lower) == 'darwin'
  ansible.builtin.set_fact:
    krew_bin: /opt/homebrew/bin/kubectl-krew

- name: Update Krew index
  changed_when: krew_update.rc == 0
  ansible.builtin.command:
    cmd: "{{ krew_bin }} update"
  register: krew_update

- name: Install plugins
  changed_when: krew_install.rc == 0
  ansible.builtin.command:
    cmd: "{{ krew_bin }} install {{ item }}"
  loop: "{{ krew_plugins }}"
  register: krew_install
