# code: language=ansible
---
- name: Import rpm key
  become: true
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Setup vscode repo
  become: true
  ansible.builtin.yum_repository:
    name: vscode
    description: Microsoft vscode software repository
    mode: "0644"
    baseurl:
      - https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode
  become: true
  ansible.builtin.dnf:
    name:
      - code
    state: present
    update_cache: true
